name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker WIS2Bridge image
        with:
          image: tproescholdt/wis2kafkabridge
          tags: v1, latest
          registry: docker.io
          dockerfile: wis2bridge/Dockerfile
          directory: wis2bridge/.
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker notifications-dedup image
        with:
          image: tproescholdt/wis2obsproc-notification-dedup
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile-notification-dedup
          directory: .
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}